### ISSUE TITLE
Redetached window becomes content of DesktopPane

### ISSUE THREAD

**Issue by vindis** [kordamp/desktoppanefx#11]
Hi. I found this behaviour:

1. Open new window on desktop pane
2. Maximize it
3. Click detach
4. Click attach
5. Click Maximize

After the last step the content of window becomes content of the desktop pane. Whatever was on the desktop pane gets lost.

Thanks

**Comment by aalmiray** [comment]
Thank you for the bug report! There are still some glitches with the detach function that we’d like to fix. We’ll follow up with the information you provided and hopefully post a fix quite soon.
